name: Compile CV

on:
  push:
    branches: [ main ]
    paths:
      - 'CV/**'    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            biber \
            latexmk

      - name: Compile CV PDF
        working-directory: ./CV
        run: |
          pdflatex main.tex
          biber main
          pdflatex main.tex
          pdflatex main.tex

      - name: Move PDF
        run: |
          mkdir -p assets/pdf
          mv CV/main.pdf assets/pdf/CV.pdf

      - name: Commit compiled PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/pdf/CV.pdf
          git commit -m "Update compiled CV PDF [skip ci]" || echo "No changes to commit"
          git push